server:
  port: 9000
spring:
  profiles:
    active: dbs-tables
  application:
    name: javabb-demo-sharding-jdbc
mybatis:
  mapper-locations: classpath*:cn/javabb/sharding/mapper/*.xml
  type-aliases-package: cn.javabb.sharding.entity